from datetime import date
from typing import Protocol

from aos.domain.finance.records import Certainty, ExpenseRecord, RevenueRecord
from aos.domain.goals.goal import Goal


class RevenueRepository(Protocol):
    def add(self, record: RevenueRecord) -> None: ...

    def all(self, certainty: Certainty | None = None) -> list[RevenueRecord]: ...

    def since(self, start: date) -> list[RevenueRecord]: ...


class ExpenseRepository(Protocol):
    def add(self, record: ExpenseRecord) -> None: ...

    def all(self) -> list[ExpenseRecord]: ...

    def since(self, start: date) -> list[ExpenseRecord]: ...


class GoalRepository(Protocol):
    def all(self) -> list[Goal]: ...

    def get(self, key: str) -> Goal | None: ...

    def children_of(self, key: str) -> list[Goal]: ...

    def save(self, goal: Goal) -> None: ...

    def add_missing(self, goals: list[Goal]) -> list[str]:
        """Seeding never overwrites a target the user has set."""
        ...
